# Generated by Django 5.2.3 on 2025-07-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_session_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
