[tool.poetry]
name = "module-7"
version = "0.1.0"
description = ""
authors = ["Alexey Stolbov <alstoff@live.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.3"
djangorestframework = "^3.16.0"
django-environ = "^0.12.0"
psycopg2 = "^2.9.10"
pillow = "^11.2.1"
django-filter = "^25.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
