# Generated by Django 5.2.3 on 2025-07-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
